TF_DOCS := $(shell which terraform-docs 2> /dev/null)
TF_FILES = $(shell find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
TF_TESTS = $(shell find ./tests -type f -name "*.tf" -exec dirname {} \;|sort -u)

SEMTAG=tools/semtag
TAG_QUERY=v1.0.0..

scope ?= "minor"

define terraform-docs
	$(if $(TF_DOCS),,$(error "terraform-docs revision >= a8b59f8 is required (https://github.com/segmentio/terraform-docs)"))

	@echo '<!-- DO NOT EDIT. THIS FILE IS GENERATED BY THE MAKEFILE. -->' > $1
	@echo '# Terraform variables inputs and outputs' >> $1
	@echo $2 >> $1
	terraform-docs markdown $3 $4 $5 $6 >> $1
endef

.PHONY: validate
validate:
	@for m in $(TF_TESTS); do cd "$$m"; terraform init > /dev/null 2>&1; echo "$$m: ";terraform validate "."; cd -; done
	
.PHONY: fmt
fmt:
	@for m in $(TF_FILES); do (terraform fmt -diff "$$m" && echo "√ $$m"); done
	
.PHONY: changelog
changelog:
	git-chglog -o CHANGELOG.md $(TAG_QUERY)

.PHONY: release
release:
	$(SEMTAG) final -s $(scope)

.PHONY: docs
docs:
	$(call terraform-docs, docs/variables.md, \
		'This document gives an overview of variables used in the aws asg lifecycle module.\n', \
		./)